version: '3'
services:
  web:
    image: diakarou/calculator-web:v1.0
    ports:
      - "3000:3000"

  api:
    image: diakarou/calculator-api:v1.0
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: diakarou/calculator-mysql:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: "sokh"
      MYSQL_DATABASE: "calculator_bd"
    ports:
      - "3306:3306"
